"""Changed the type of role in the User table

Revision ID: 48426b6e7c12
Revises: 
Create Date: 2025-07-26 21:28:51.454437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48426b6e7c12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('ADMIN', 'USER', 'GUEST', name='userrole'),
               postgresql_using="role::userrole",
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', 'GUEST', name='userrole'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
