name: Ping Render Backend

on:
  schedule:
    # Runs at 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00 UTC
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Server
        run: curl -k -f "https://bagent.onrender.com/health" || true
